---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  namespace: demo-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: downloadv2
  template:
    metadata:
      labels:
        app: nginx
        version: downloadv2
    spec:
      containers:
      - name: nginx
        image: "nginx:1.15.3-alpine"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-content
        hostPath:
          path: /home/cord/nginx-content
          type: Directory
